### ISSUE TITLE
Конфиг

### ISSUE THREAD

**Issue by pavelzarubin** [gshumilin/learning-bot#13]
Поля ```tgToken```, ```tgTimeout``` лучше переименовать в token и timeout. Поля  ```tgRequestHost``` и ```tgRequestPort``` лучше вообще убрать,  а адрес сервера захардкодить, так как он скорее всего никогда не изменится, а если дадим пользователю возможность его изменять в конфиге, это приведет к не нужным ошибкам.

**Comment by gshumilin** [comment]
закрываю по согласованию в лс
