### ISSUE TITLE
Ревью 1

### ISSUE THREAD

**Issue by Presto-Con-Fuoco** [gshumilin/learning-bot#20]
1. https://github.com/gshumilin/learning-bot/blob/f13a697b3409e15e84f1cb58d7a87aa3f5a73d53/src/Types/Config.hs#L24-L42 Этот фрагмент явный претендент на то, чтобы переписать его через deriving, т.к. ничего сложного тут нет, один сплошной boilerplate.
2. https://github.com/gshumilin/learning-bot/blob/f13a697b3409e15e84f1cb58d7a87aa3f5a73d53/src/Types/Config.hs#L44 Мне кажется UnknownFrontend тут не нужно, в соответствующей ситуации можно просто использовать тип `Maybe FrontEndType`. Сюда же про автоматический deriving (deriving ToJSON, FromJSON).
3. https://github.com/gshumilin/learning-bot/blob/f13a697b3409e15e84f1cb58d7a87aa3f5a73d53/src/Types/Config.hs#L42 Вместо паттерн матчинга по Object можно было бы взять функцию withObject. Но если всё сделать через deriving, то и она тут не нужна.
4. https://github.com/gshumilin/learning-bot/blob/8e54886b9320e11cfc057a1ddbb25bef186b2491/src/Types/Log.hs#L7-L9 Не используй в коде кириллицу, пиши все комментарии на английском. Мало ли кому придётся читать твой код.
5. В том же модуле, чуть ниже - сделай автоматический дерайвинг. И вообще сделай по всему проекту. Если не дерайвить такие инстансы, то можно большую часть своего времени тратить на это, а не на осмысленный код.
6. https://github.com/gshumilin/learning-bot/blob/8e54886b9320e11cfc057a1ddbb25bef186b2491/src/Types/Message.hs#L8 Убери UnknownMessage и сделай автоматический дерайвинг. Кроме того, из описания типа не сразу ясно, что за Text имеется в виду, например, в случае стикера. Что это? Айдишник стикера, картинка стикера, ссылка на стикер? Добавь, например, селекторы рекордов сюда. Кроме того, для любых айдишников вместо простого Text можно использовать newtype Id a = Id {getId :: Text}, где a обозначает, к какому типу относится айдишник. Для стикеров получится `Id Sticker`, Sticker это либо какой-то настоящий рекорд, а если его нет, то можно сделать тип без конструкторов: data Sticker, и использовать его.
7. Добавь возможность писать логи не только в файл, а в любой дескриптор, конкретно меня интересует stderr.
8. https://github.com/gshumilin/learning-bot/blob/8e54886b9320e11cfc057a1ddbb25bef186b2491/src/App/TgBotRun.hs#L24 Во-первых, я бы ещё подумал, не использовать ли здесь Error вместо Warning. Во-вторых, похоже что это сообщение не несёт никакой пользы, т.к. непонятно, что это за JSON и как это пофиксить. Добавь сам JSON тоже в логи.
9. https://github.com/gshumilin/learning-bot/blob/8e54886b9320e11cfc057a1ddbb25bef186b2491/src/Implementations/Logging.hs#L9-L16 Мне кажется не очень хорошей идеей на каждую запись в лог открывать файл и потом его закрывать, лучше держать файл открытым всё время.
10. https://github.com/gshumilin/learning-bot/blob/8e54886b9320e11cfc057a1ddbb25bef186b2491/src/App/TgBotRun.hs#L33 Мне кажется, что Warning это какая-то нездоровая ситуация, которая явно не является ошибкой и при которой тем не менее возможна дальнейшая работа. А тут вроде бы всё абсолютно штатно работает, апдейты обрабатываются, я бы скорее это сделал DEBUG или INFO.
11. https://github.com/gshumilin/learning-bot/blob/8e54886b9320e11cfc057a1ddbb25bef186b2491/src/App/TgBotRun.hs#L19 По сути ты таскаешь и Config, и список с состояниями пользователей, но делаешь это по-разному. Я бы объединил всё это вместо в один рекорд, который бы уже был под ReaderT, можно назвать её, например, Environment. Но при этом нам, естественно, нужно изменять некоторую часть из всего этого Environment. Это можно сделать, например, через IORef. 
12. https://github.com/gshumilin/learning-bot/blob/8e54886b9320e11cfc057a1ddbb25bef186b2491/src/App/TgBotRun.hs#L64 Вместо явной рекурсии лучше выделить одну функцию, которая полностью будет отвечать за отправку одного сообщения, а потом сделать на неё replicateM.
13. https://github.com/gshumilin/learning-bot/blob/8e54886b9320e11cfc057a1ddbb25bef186b2491/src/App/TgBotRun.hs#L102-L106 А если бы надо было 20 кнопок, тоже вручную бы писал? :) Переделай это, пожалуйста
14. https://github.com/gshumilin/learning-bot/blob/8e54886b9320e11cfc057a1ddbb25bef186b2491/src/App/TgBotRun.hs#L110-L117 Как минимум часть из этого точно можно вынести в отдельную функцию, а в ещё одну отдельную функцию - конструирование хоста телеграмма (с учетом токена)
15. https://github.com/gshumilin/learning-bot/blob/8e54886b9320e11cfc057a1ddbb25bef186b2491/src/App/TgBotRun.hs#L147-L148 Просто сделай на предпоследнюю точку `void`, тогда результат проигнорируется

**Comment by gshumilin** [comment]
Насчёт пункта 6. UnknownMessage нужен мне для корректного парсинга обновлений и ответа клиенту, если он пришлёт неизвестное медиа. С другой стороны - в типе Update можно поменять тип приходящего сообщения на Maybe Message и перед обработкой сообщений добавить проверку. Большой выгоды от этих изменений я пока не вижу и в требованиях для бота каких-то таких условий я не нашёл. Точно ли это необходимо менять и в чём выгода? Если точно необходимо, напиши, пожалуйста, и я перепишу. Пока оставлю как есть.

Согласен с тем, что не понятно, что там лежит в стикере. Создал пока синоним для ясности. Этого достаточно? Создавать обёртку для всех Id не стал, потому что только со стикером есть проблема с читабельностью. Если ты считаешь, что всё-таки надо создать, то напиши, пожалуйста.

**Comment by Presto-Con-Fuoco** [comment]
> Насчёт пункта 6. UnknownMessage нужен мне для корректного парсинга обновлений и ответа клиенту, если он пришлёт неизвестное медиа. С другой стороны - в типе Update можно поменять тип приходящего сообщения на Maybe Message и перед обработкой сообщений добавить проверку. Большой выгоды от этих изменений я пока не вижу и в требованиях для бота каких-то таких условий я не нашёл. Точно ли это необходимо менять и в чём выгода? Если точно необходимо, напиши, пожалуйста, и я перепишу. Пока оставлю как есть.
> 
> Согласен с тем, что не понятно, что там лежит в стикере. Создал пока синоним для ясности. Этого достаточно? Создавать обёртку для всех Id не стал, потому что только со стикером есть проблема с читабельностью. Если ты считаешь, что всё-таки надо создать, то напиши, пожалуйста.

Выгода в том, что удобно отделять ошибочные состояния от корректных. Если у тебя Maybe Message, ты обрабатываешь Nothing и дальше работаешь с хорошим чистым Message, а все ошибки остаются в прошлом. В твоем же случае где бы ты ни обратился к Message, всегда может оказаться, что там ошибка. А с чисто технической точки зрения разницы нет, т.к. Message с UnknownMessage и Maybe Message без него - изоморфны. Но при этом во втором случае ты не плодишь лишние сущности

**Comment by gshumilin** [comment]
готов ПР для 12 и 13 пункта. Не вижу тут инфы об этом. Похоже, забыл где-то указать метку ишью

**Comment by gshumilin** [comment]
11 пункт готов. Создал для него ПР. Долго экспериментировал с монадой IORef, получилось немного не элегантно. Если захочешь, можем что-то поправить или не мёрджить вовсе)

**Comment by gshumilin** [comment]
Ишью закрываю по согласованию в лс.
