### ISSUE TITLE
Вручную модифицированный .cabal файл

### ISSUE THREAD

**Issue by olegromashin** [gshumilin/learning-bot#4]
Для управления зависимостями мы можем использовать stack или cabal. Если мы используем cabal, то меняем `.cabal`-файл, в случае со stack мы меняем `package.yaml` и `stack.yaml` файлы.
Если мы решили использовать stack, то при сборке проекта cabal-файл всё равно используется, просто stack за нас его меняет. Если самому что-то поменять в cabal-файле, то stack больше не будет автоматически менять cabal-файл. Чтобы это исправить, надо удалить cabal-файл и stack его сам сгенерирует при следующей сборке проекта, и дальше stack сам будет его менять при необходимости.
У тебя как раз такая ситуация, ты, видимо, редактировал cabal-файл и stack-файлы игнорируются. Надо исправить, т. к. мы пользуемся stack'ом сейчас.

**Comment by gshumilin** [comment]
Мерси. Файл удалил и пересобрал проект.

**Comment by olegromashin** [comment]
Можешь запушить изменения? А то если я сейчас репозиторий склонирую, то этот недочёт так и останется.

**Comment by gshumilin** [comment]
> Можешь запушить изменения? А то если я сейчас репозиторий склонирую, то этот недочёт так и останется.

Это как?

**Comment by olegromashin** [comment]
ну у тебя все изменения сейчас локально на компьютере, в репозитории здесь на Гитхабе их нет. их надо сюда отправить, чтобы они тут тоже были

**Comment by gshumilin** [comment]
Готово, пушнуто, аппрувнуто, смёрджено
