### ISSUE TITLE
Закомментированные без пояснения участки кода

### ISSUE THREAD

**Issue by olegromashin** [gshumilin/learning-bot#5]
В файлах исходного кода не должно быть закомментированных без пояснения строчек кода. Другие разработчики не смогут понять смысл таких участков и не будут знать можно ли их удалить.

https://github.com/gshumilin/learning-bot/blob/a97c579c3c980e075750e73f19b8560ccf09fd66/src/Realisations/Config.hs#L12

**Comment by gshumilin** [comment]
Удалил эти строчки. Проверил остальные файлы - лишних комментариев нет
