### ISSUE TITLE
Нет проверки числа повторений.

### ISSUE THREAD

**Issue by pavelzarubin** [gshumilin/learning-bot#9]
При вызове ```/repeat``` в боте, я могу задать любое число повторений, даже отрицательное. А должно быть от 1 до 5.

**Comment by gshumilin** [comment]
Исправил. Изначально указал не тот логический оператор в функции проверки числа повторений.

**Comment by pavelzarubin** [comment]
Исправления вноси с помощью пул-реквестов

**Comment by gshumilin** [comment]
Я перенёс проверку числа повторений в тестируемую часть. Сейчас добавлю ещё два теста и сделаю пул-реквест
